[tool.poetry]
name = "ts-train"
version = "0.1.0"
description = ""
authors = ["AGI3YDM <luca.sorrentino@agilelab.it>"]
readme = "README.md"
packages = [{include = "ts_train", from = "src"}]

[tool.poetry.dependencies]
python = "^3.10"
pre-commit = "^3.3.3"
pyspark = "^3.4.1"
omegaconf = "^2.3.0"
pydantic = "^2.0"
pydantic-settings = "^2.0.0"
pytest = "^7.4.0"
loguru = "^0.7.0"
typing-extensions = "^4.7.1"
pytest-cov = "^4.1.0"



[tool.ruff]
ignore = ["F403", "F405"] # allow to import *

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
